version: '3'
services:
  app:
    container_name: app  
    build: ./docker/php
    volumes:
      - .:/var/www
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 8000:80 
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
      PMA_ARBITRARY: 1
      PMA_USER: 'root'
      PMA_PASSWORD: ''
    ports:
    - '127.0.0.1:8080:80'
  db:
    image: mysql:5.7 
    container_name: db
    environment: 

    # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: database
      # MYSQL_USER: db-user
      # # MYSQL_PASSWORD: db-pass
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf 
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306